name: Release
on:
  release:
    types: [created]

jobs:
  node-module-npmjs:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          registry-url: https://registry.npmjs.org/
      - name: Build
        run: npm install
      - name: Install Emscripten
        uses: mymindstorm/setup-emsdk@v14
        with:
          version: 3.1.6
      - name: Generate parser WASM
        run: npx tree-sitter build-wasm
      - name: Publish
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}

  rust-crate:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v4
      - name: Use stable rust toolchain
        run: rustup default stable
      - name: Build
        run: cargo check
      - name: Publish
        run: cargo publish --token ${{secrets.CRATES_AUTH_TOKEN}}

